import type { Metadata } from "next";
import { ReactNode, FC } from "react";

import { BaseLayout } from "@widgets/layouts";

import "@styles/styles.scss";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

type RootLayoutProps = {
	children: ReactNode;
};

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
	return (
		<html lang="en">
			<body>
				<BaseLayout>{children}</BaseLayout>
			</body>
		</html>
	);
};

export default RootLayout;
